import { CirclePlus, Clock3, IndianRupee, Power } from "lucide-react";
import Image from "next/image";
import { PageHeading } from "@/components/page-heading";
import { StatusPill } from "@/components/status-pill";
import { getPoojas } from "@/lib/data";
import { savePooja, togglePooja } from "@/app/actions/content";
import type { Pooja } from "@/lib/types";

function PoojaForm({ pooja }: { pooja?: Pooja }) {
  return <form action={savePooja} className="editor-form">{pooja && <input type="hidden" name="id" value={pooja.id}/>}<div className="form-grid"><label>Service name<input name="name" defaultValue={pooja?.name} required/></label><label>URL slug<input name="slug" defaultValue={pooja?.slug} required pattern="[a-z0-9-]+"/></label><label>Kannada name<input name="kannada_name" defaultValue={pooja?.kannada_name}/></label><label>Image URL<input name="image_url" type="url" defaultValue={pooja?.image_url || ""}/></label><label>Duration (minutes)<input name="duration_minutes" type="number" min="15" defaultValue={pooja?.duration_minutes || 120} required/></label><label>Starting price (INR)<input name="base_price_inr" type="number" min="0" defaultValue={pooja?.base_price_inr || 0} required/></label><label className="span-2">Description<textarea name="description" rows={3} defaultValue={pooja?.description}/></label><label>SEO title<input name="seo_title"/></label><label>SEO description<input name="seo_description"/></label></div><label className="check-row"><input name="is_active" type="checkbox" defaultChecked={pooja?.is_active ?? true}/><span>Visible to customers and eligible priests</span></label><div className="form-actions"><button className="primary-button">{pooja ? "Save changes" : "Create puja"}</button></div></form>;
}

export default async function PoojasPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [poojas, query] = await Promise.all([getPoojas(), searchParams]);
  return <><PageHeading eyebrow="Content management" title="Puja catalog" description="The service taxonomy shared by customer requests, priest specialties, bidding, and search pages."/><details className="create-drawer" open={!poojas.length}><summary><CirclePlus size={18}/>Add a new puja</summary><PoojaForm/></details>{query.error && <div className="notice error">{decodeURIComponent(query.error)}</div>}<section className="catalog-list">{poojas.map((pooja) => <article className="catalog-row" key={pooja.id}><div className="catalog-image">{pooja.image_url ? <Image src={pooja.image_url} alt="" width={72} height={72} unoptimized/> : <span>{pooja.name.slice(0, 2).toUpperCase()}</span>}</div><div className="catalog-copy"><div><h2>{pooja.name}</h2><StatusPill status={pooja.is_active ? "active" : "inactive"}/></div><p>{pooja.description || "No description has been added."}</p><span className="meta"><Clock3 size={15}/>{pooja.duration_minutes} min <IndianRupee size={15}/>{pooja.base_price_inr.toLocaleString("en-IN")}</span></div><details className="row-editor"><summary className="secondary-button">Edit</summary><div className="popover-editor"><PoojaForm pooja={pooja}/></div></details><form action={togglePooja}><input type="hidden" name="id" value={pooja.id}/><input type="hidden" name="next" value={String(!pooja.is_active)}/><button className="icon-button" title={pooja.is_active ? "Deactivate" : "Activate"}><Power size={17}/></button></form></article>)}</section></>;
}
