import { CirclePlus, ExternalLink, SearchCheck } from "lucide-react";
import { saveKeywordCluster } from "@/app/actions/content";
import { PageHeading } from "@/components/page-heading";
import { StatusPill } from "@/components/status-pill";
import { getSeoData } from "@/lib/data";

export default async function SeoPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [{ clusters, pages }, query] = await Promise.all([getSeoData(), searchParams]);
  return <><PageHeading eyebrow="Organic growth" title="Search, GEO and answer strategy" description="Plan intent-led keyword clusters, publish useful pages, and measure discovery without generating doorway-page spam."/>{query.error && <div className="notice error">{decodeURIComponent(query.error)}</div>}<section className="seo-layout"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Strategy backlog</p><h2>Keyword clusters</h2></div><span>{clusters.length} clusters</span></div><div className="cluster-list">{clusters.map((cluster) => <div className="cluster-row" key={cluster.id}><SearchCheck size={18}/><span><strong>{cluster.name}</strong><small>{cluster.primary_keyword} · {cluster.locale}</small></span><StatusPill status={cluster.status}/></div>)}{!clusters.length && <div className="empty-state">No keyword clusters created.</div>}</div></div><form action={saveKeywordCluster} className="panel editor-form"><div className="section-title compact"><CirclePlus size={18}/><div><h2>New keyword cluster</h2><p>One intent, one useful destination.</p></div></div><label>Cluster name<input name="name" required placeholder="Satyanarayan puja in Bengaluru"/></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" placeholder="satyanarayan-bengaluru"/></label><label>Primary keyword<input name="primary_keyword" required/></label><label>Supporting keywords<input name="supporting_keywords" placeholder="comma, separated, terms"/></label><div className="form-grid"><label>Intent<select name="intent"><option value="local">Local</option><option value="transactional">Transactional</option><option value="commercial">Commercial</option><option value="informational">Informational</option></select></label><label>Locale<input name="locale" defaultValue="en-IN"/></label><label>City slug<input name="city_slug" placeholder="bengaluru"/></label><label>Puja slug<input name="pooja_slug" placeholder="satyanarayan"/></label></div><button className="primary-button">Create cluster</button></form></section><section className="table-panel"><div className="table-toolbar"><strong>Content performance</strong><span>Imported daily from approved analytics sources</span></div><div className="data-table"><div className="table-row seo-table table-head"><span>Page</span><span>Impressions</span><span>Clicks</span><span>Sessions</span><span>Conversions</span></div>{pages.map((page) => <div className="table-row seo-table" key={page.id}><span><strong>{page.title}</strong><small>/{page.slug}</small></span><span>{page.impressions_30d}</span><span>{page.clicks_30d}</span><span>{page.sessions_30d}</span><span>{page.conversions_30d}</span></div>)}</div></section><div className="principle-note"><ExternalLink size={18}/><p><strong>Editorial policy</strong><span>Every published page must answer a real family need, use accurate service data, and provide unique local value. AI assistance does not replace human review.</span></p></div></>;
}

