import Link from "next/link";
import { Activity, ArrowUpRight, BookOpenCheck, CalendarRange, FileCheck2, ScanSearch, UserRoundCheck, UsersRound } from "lucide-react";
import { ActivityChart } from "@/components/charts";
import { Kpi } from "@/components/kpi";
import { PageHeading } from "@/components/page-heading";
import { getDashboardData } from "@/lib/data";

export default async function DashboardPage() {
  const { active, daily, features, totals } = await getDashboardData();
  return <><PageHeading eyebrow="Live operations" title="Marketplace overview" description="A current view of demand, supply, engagement, and published content." actions={<Link className="primary-button" href="/content/pages/new">Create page <ArrowUpRight size={16}/></Link>}/><section className="kpi-grid"><Kpi label="Daily active users" value={active.daily_active_users} detail={`${active.weekly_active_users} active this week`} icon={Activity} tone="orange"/><Kpi label="Monthly active users" value={active.monthly_active_users} detail={`${active.sessions_30d} sessions in 30 days`} icon={UsersRound}/><Kpi label="Verified priests" value={totals.priests} detail={`${totals.openRequests} open ceremony requests`} icon={UserRoundCheck} tone="green"/><Kpi label="Published pages" value={totals.publishedPages} detail={`${totals.users} active accounts`} icon={FileCheck2}/></section><section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">30-day trend</p><h2>Demand and activity</h2></div><span className="legend"><i/>Active users <i className="dark"/>Requests</span></div><ActivityChart data={daily}/></article><article className="panel feature-panel"><div className="panel-heading"><div><p className="eyebrow">Product signals</p><h2>Most-used features</h2></div><Link href="/analytics" className="text-link">View report</Link></div><div className="feature-list">{features.length ? features.map((feature, index) => <div className="feature-row" key={feature.event_name}><span className="rank">{String(index + 1).padStart(2, "0")}</span><span><strong>{feature.event_name.replaceAll("_", " ")}</strong><small>{feature.unique_users} users · {feature.unique_sessions} sessions</small></span><b>{feature.total_events}</b></div>) : <div className="empty-state">No feature events recorded in the last 30 days.</div>}</div></article></section><section className="shortcut-grid"><Link href="/content/poojas"><CalendarRange/><span><strong>Manage puja catalog</strong><small>Services, pricing, durations, images</small></span><ArrowUpRight/></Link><Link href="/priests"><BookOpenCheck/><span><strong>Review priest applications</strong><small>Verification, coverage, specialties</small></span><ArrowUpRight/></Link><Link href="/seo"><ScanSearch/><span><strong>Grow organic discovery</strong><small>Keyword clusters, GEO and AEO pages</small></span><ArrowUpRight/></Link></section></>;
}

