import { AlertTriangle, MailPlus, UserCog } from "lucide-react";
import { changeAccountRole, inviteAccount, reportAccount, resolveUserReport, setAccountState } from "@/app/actions/content";
import { PageHeading } from "@/components/page-heading";
import { StatusPill } from "@/components/status-pill";
import { getModerationData, getPeopleData } from "@/lib/data";

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ users }, moderation, query] = await Promise.all([getPeopleData(), getModerationData(), searchParams]);
  return <><PageHeading eyebrow="Identity and access" title="Customers, priests, and operators" description="Invite accounts, manage access, report risk, and review moderation history. Every privileged action is written to the audit log."/>{query.error && <div className="notice error">{decodeURIComponent(query.error)}</div>}{query.success && <div className="notice success">{decodeURIComponent(query.success)}</div>}
    <details className="create-drawer"><summary><MailPlus size={17}/>Invite a customer, priest, or operator</summary><form action={inviteAccount} className="editor-form"><div className="form-grid"><label>Full name<input name="full_name" required placeholder="Account holder name"/></label><label>Email<input name="email" type="email" required placeholder="name@example.com"/></label><label>Role<select name="role" defaultValue="priest"><option value="priest">Priest</option><option value="customer">Customer</option><option value="support">Support</option><option value="admin">Administrator</option></select></label></div><div className="form-actions"><button className="primary-button"><MailPlus size={15}/>Send secure invite</button></div></form></details>
    <div className="table-panel"><div className="table-toolbar"><strong>{users.length} recent accounts</strong><span>Latest 100</span></div><div className="data-table"><div className="table-row account-table table-head"><span>Account</span><span>Role and access</span><span>Contact</span><span>Moderation</span></div>{users.map((user) => <div className="table-row account-table" key={user.id}><span><strong>{user.full_name || "Unnamed account"}</strong><small>{user.email || user.id}</small><small>Joined {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(user.created_at))}</small></span><span><StatusPill status={user.is_active ? "active" : "inactive"}/><form action={changeAccountRole} className="inline-action"><input type="hidden" name="id" value={user.id}/><select name="role" defaultValue={user.role}><option value="customer">Customer</option><option value="priest">Priest</option><option value="support">Support</option><option value="admin">Admin</option>{user.role === "super_admin" && <option value="super_admin">Super admin</option>}</select><button className="secondary-button" disabled={user.role === "super_admin"}><UserCog size={14}/>Apply</button></form></span><span>{user.phone || "Phone not provided"}<small>{user.moderated_at ? `Last moderated ${new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(user.moderated_at))}` : "No moderation action"}</small></span><span><form action={setAccountState} className="inline-action"><input type="hidden" name="id" value={user.id}/><input type="hidden" name="active" value={String(!user.is_active)}/><input name="note" placeholder="Reason" required/><button className={user.is_active ? "danger-button" : "secondary-button"} disabled={user.role === "super_admin"}>{user.is_active ? "Suspend" : "Reactivate"}</button></form><details className="report-action"><summary><AlertTriangle size={14}/>Report account</summary><form action={reportAccount} className="compact-form"><input type="hidden" name="id" value={user.id}/><select name="category" defaultValue="conduct"><option value="identity">Identity</option><option value="conduct">Conduct</option><option value="spam">Spam</option><option value="payment">Payment</option><option value="safety">Safety</option><option value="other">Other</option></select><input name="details" required placeholder="What happened?"/><button className="secondary-button">Add report</button></form></details></span></div>)}</div></div>
    <section className="table-panel"><div className="table-toolbar"><strong>Moderation queue</strong><span>{moderation.reports.length} reports</span></div><div className="data-table"><div className="table-row report-table table-head"><span>Reported account</span><span>Reason</span><span>Status</span><span>Resolution</span></div>{moderation.reports.map((report) => { const account = Array.isArray(report.app_users) ? report.app_users[0] : report.app_users; return <div className="table-row report-table" key={report.id}><span><strong>{account?.full_name || "Unknown account"}</strong><small>{account?.email || report.reported_user_id}</small></span><span><strong>{report.category}</strong><small>{report.details || "No details supplied"}</small></span><span><StatusPill status={report.status}/><small>{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(report.created_at))}</small></span><span><form action={resolveUserReport} className="inline-action"><input type="hidden" name="id" value={report.id}/><select name="status" defaultValue={report.status}><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select><input name="resolution_note" required placeholder="Resolution note"/><button className="secondary-button">Save</button></form></span></div>})}{!moderation.reports.length && <div className="empty-state roomy">No reports are waiting for review.</div>}</div></section>
  </>;
}
